FROM ubuntu:16.04
RUN apt update
RUN apt-get -y install nginx
COPY fastcgi.conf /etc/nginx/fastcgi.conf
COPY php.conf.inc /etc/nginx/conf.d/php.conf.inc
COPY site.conf /etc/nginx/sites-available/default

CMD /usr/sbin/nginx -g 'daemon off;'
